### ISSUE TITLE
Improve

### ISSUE THREAD

**Issue by realitix** [bglgwyng/pyVulkan#12]
Hello @bglgwyng.

I have written a wrapper too but without CFFI [cvulkan](https://github.com/realitix/cvulkan).
It works pretty well but it's hard to maintain it, so I want to go for a CFFI version.

I could rewrite it with CFFI but I think it would be better to work with you on this.
I am currently writing a Vulkan engine in python [vulk](https://github.com/realitix/vulk) and I would like to pass to the cffi version in a transparent way. Here what must be done (I will help you of course):

- `@vkDebugReportCallbackEXT` should not be asked from an API point of view. I just want to pass a function to `VkDebugReportCallbackCreateInfoEXT` (cvulkan handle that). It's not hard to do.
- All object that I receive from vulkan call must be easy to manipulate python object. I don't want to decode cffi string, I *just* want python string (cvulkan handle that).
- Some constants should be added: `UINT64_MAX` instead of `ffi.cast('uint64_t', -1)`

The developer using pyVulkan doesn't have to know cffi to use it.
Next we will do a proper documentation.

Moreover, can you rename the project pyvulkan instead of pyVulkan, it's easier with only lowercase.

I am going to fork your project and make pull request but I would prefer to have write access to the repo. I know it's a big demand but there is a lot to do! Moreover, it's easier to maintain the project if we are together.

Thanks in advance.

Jean-Sébastien Bevilacqua

**Comment by realitix** [comment]
I have written the new wrapper which is a big improvement over pyVulkan.

If you come here, can you update your Readme to link with the new wrapper.

https://github.com/realitix/vulkan

**Comment by bglgwyng** [comment]
Sorry for too late reply. I should have done what you suggested. I'll announce this repository is deprecated and write a link to your repository.

**Comment by realitix** [comment]
Thanks @bglgwyng! I will talk to europython thanks to cffi so no problem!
