### ISSUE TITLE
graphics_queue_node_index and present_queue_node_index should be compared against None not False

### ISSUE THREAD

**Issue by griffin2000** [bglgwyng/pyVulkan#14]
There is a logic error in Cube.py graphics_queue_node_index and present_queue_node_index are compared as boolean to test if they've been set. This fails in the case they are set to 0 (which is a valid index). They should be compared against None instead:

```
        for i, v in enumerate(queue_props):
            if v.queueFlags & VK_QUEUE_GRAPHICS_BIT:
                if graphics_queue_node_index==None:
                    graphics_queue_node_index = i

                if support_presents[i] == VK_TRUE:
                    graphics_queue_node_index = i
                    present_queue_node_index = i
                    break

        if present_queue_node_index==None:
            for i, v in enumerate(support_presents):
                if v == VK_TRUE:
                    present_queue_node_index = i
```

**Comment by griffin2000** [comment]
Created PR for this change: https://github.com/bglgwyng/pyVulkan/pull/15

**Comment by realitix** [comment]
Hello @griffin2000. This repository is not maintained anymore, its author doesn't answer anymore. Don't loose your time here and focus on https://github.com/realitix/vulkan

**Comment by realitix** [comment]
Take a look at #12 , it's why I restarted the project!

**Comment by realitix** [comment]
Take a look at #12 , it's why I restarted the project!
